name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@refs/pull/:prNumber/merge
      - uses: actions/setup-node@refs/pull/:prNumber/merge
        with:
          node-version: '16.14'
      - run: npm install
      - run: npm run buildProd
